name: Our Custom workflow

on:
  push:
    branches: ["main"]

jobs:
  setupSytem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Download Docker install script"
        run: curl -fsSL https://get.docker.com -o get-docker.sh
      - name: Install Docker with script
        run: sudo sh ./get-docker.sh
      - name: Check if docker is installed
        run: docker version
      - name: Login to dockerhub
        run: docker login -u simplewilliamz -p ${{ secrets.DOCKER_PASSWORD }}
  build_backend_docker_file:
    runs-on: ubuntu-latest
    needs: setupSytem
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Navigate to backend folder
        run: echo "Going to backend"
      - name: Build container
        run: docker build -t simplewilliamz/backend-go-api .
      - name: Push image to dockerhub
        run: docker push simplewilliamz/backend-go-api
  build_frontend_docker_file:
    runs-on: ubuntu-latest
    needs: setupSytem
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Navigate to frontend folder
        run: echo "Go frontend folder"
      - name: Build container
        run: docker build -t simplewilliamz/backend-go-api .
      - name: Push image to dockerhub
        run: docker push simplewilliamz/backend-go-api